"""Подготовка изолированного инстанса NetBox для одной цели тестирования."""

from __future__ import annotations

import re
import secrets
import shutil
from dataclasses import dataclass
from pathlib import Path

from .config import NetBoxSpec, PluginSpec
from .process import CommandResult, clean_env, run_logged

CONFIGURATION_TEMPLATE = """# Generated by netbox-plugins-compatibility. Do not edit.
ALLOWED_HOSTS = ['*']
{database_key} = {database!r}
REDIS = {redis!r}
SECRET_KEY = {secret_key!r}
DEBUG = False
# Даёт анонимный доступ к /api/status/, по которому проверяется стадия startup.
LOGIN_REQUIRED = False
PLUGINS = {plugins!r}
PLUGINS_CONFIG = {plugins_config!r}
"""


@dataclass(frozen=True)
class Backends:
    """Координаты Postgres и Redis, которые раннер получает извне."""

    db_host: str
    db_port: int
    db_user: str
    db_password: str
    db_maintenance: str
    redis_host: str
    redis_port: int
    redis_password: str


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


class SourceCache:
    """Один клон NetBox на прогон; на каждую цель — отдельный git worktree.

    Worktree, а не повторный clone: любой ref (тег, ветка, коммит) доступен без
    повторной выкачки, а несуществующий ref честно валит `worktree add`.
    """

    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def _clone_path(self, repository: str) -> Path:
        return self.root / slugify(repository.rsplit("/", 1)[-1].removesuffix(".git"))

    def checkout(self, spec: NetBoxSpec, dest: Path, log_path: Path) -> CommandResult:
        clone = self._clone_path(spec.repository)
        env = clean_env()
        if not (clone / ".git").exists():
            result = run_logged(
                ["git", "clone", "--quiet", spec.repository, str(clone)],
                log_path,
                env=env,
            )
            if not result.ok:
                return result
        else:
            run_logged(["git", "-C", str(clone), "fetch", "--quiet", "--tags", "--prune"], log_path, env=env)

        if dest.exists():
            shutil.rmtree(dest)
        return run_logged(
            ["git", "-C", str(clone), "worktree", "add", "--detach", "--force", str(dest), spec.ref],
            log_path,
            env=env,
        )


@dataclass
class TargetEnvironment:
    """Каталоги и параметры одного инстанса NetBox."""

    target_id: str
    root: Path
    logs_dir: Path
    python: str
    backends: Backends
    plugins: tuple[PluginSpec, ...]

    @property
    def source(self) -> Path:
        return self.root / "netbox"

    @property
    def venv(self) -> Path:
        return self.root / "venv"

    @property
    def venv_python(self) -> Path:
        return self.venv / "bin" / "python"

    @property
    def manage_py(self) -> Path:
        return self.source / "netbox" / "manage.py"

    @property
    def database_name(self) -> str:
        return f"netbox_compat_{slugify(self.target_id)}"[:63]

    def log_path(self, stage: str) -> Path:
        return self.logs_dir / self.target_id / f"{stage}.log"

    def relative_log(self, stage: str, base: Path) -> str:
        return str(self.log_path(stage).relative_to(base))

    def database_key(self) -> str:
        """NetBox < 4.4 принимает только DATABASE, начиная с 4.4 — DATABASES."""
        example = self.source / "netbox" / "netbox" / "configuration_example.py"
        if example.exists() and "DATABASES = {" in example.read_text(encoding="utf-8"):
            return "DATABASES"
        return "DATABASE"

    def render_configuration(self) -> Path:
        database = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": self.database_name,
            "USER": self.backends.db_user,
            "PASSWORD": self.backends.db_password,
            "HOST": self.backends.db_host,
            "PORT": str(self.backends.db_port),
            "CONN_MAX_AGE": 300,
        }
        key = self.database_key()
        redis_common = {
            "HOST": self.backends.redis_host,
            "PORT": self.backends.redis_port,
            "USERNAME": "",
            "PASSWORD": self.backends.redis_password,
            "SSL": False,
        }
        path = self.source / "netbox" / "netbox" / "configuration.py"
        path.write_text(
            CONFIGURATION_TEMPLATE.format(
                database_key=key,
                database={"default": database} if key == "DATABASES" else database,
                redis={
                    "tasks": {**redis_common, "DATABASE": 0},
                    "caching": {**redis_common, "DATABASE": 1},
                },
                secret_key=secrets.token_urlsafe(50),
                plugins=[p.package for p in self.plugins],
                plugins_config={
                    p.package: p.plugins_config for p in self.plugins if p.plugins_config
                },
            ),
            encoding="utf-8",
        )
        return path
